export const templates = [
  {
    id: 'classic',
    name: 'Basic',
    description: 'PNG ব্যাকগ্রাউন্ড, কেন্দ্রীয় ছবি, শিরোনাম ও ওয়েবসাইটসহ পরিষ্কার লেআউট।',
    defaults: { accentColor: '#c41e3a', bgColor: '#e8e8e8', textColor: '#000000', heading: 'শিরোনাম লিখুন', subheading: 'বিস্তারিত বর্ণনা যোগ করুন', headingSize: 48, subheadingSize: 28, date: '', domain: 'sobarkotha.com' },
    html: `<div class="template-wrapper basic-template" style="--accent:{accentColor};--bg:{bgColor};--text:{textColor};--font:'{font}';--heading-size:{headingSize}px;--subheading-size:{subheadingSize}px;" data-canvas-width="1080" data-canvas-height="1080"><div class="template-background"></div><div class="basic-image-wrapper"><img class="basic-image" src="{image}" alt="Main image"></div><div class="basic-baked-logo" aria-hidden="true"></div><div class="basic-text-area"><h1 class="basic-heading">{heading}</h1><p class="basic-subheading">{subheading}</p></div><div class="basic-footer"><span class="basic-date">{date}</span></div></div>`,
    css: `.basic-template{width:1080px;height:1080px;overflow:hidden;position:relative;background:var(--bg)}.template-background{position:absolute;inset:0;background-repeat:no-repeat;background-size:100% 100%;z-index:0;pointer-events:none}.basic-template .template-background{background-image:url('./assets/basic-template.png')}.basic-image-wrapper{position:absolute;left:40px;top:40px;width:1000px;height:520px;overflow:hidden;border-radius:18px;z-index:1}.basic-image{width:100%;height:100%;object-fit:cover;display:block;transform-origin:center center}.basic-baked-logo{position:absolute;left:445px;top:535px;width:190px;height:145px;background-image:url('./assets/basic-template.png');background-repeat:no-repeat;background-size:1080px 1080px;background-position:-445px -535px;z-index:3;pointer-events:none}.basic-text-area{position:absolute;left:45px;right:45px;top:720px;z-index:4;text-align:center}.basic-heading{font:700 var(--heading-size)/1.2 var(--font),sans-serif;color:var(--text);margin:0;letter-spacing:-.02em}.basic-subheading{font:500 var(--subheading-size)/1.3 var(--font),sans-serif;color:var(--accent);margin:8px 0 0;letter-spacing:-.01em}.basic-footer{position:absolute;bottom:25px;left:45px;right:45px;display:flex;justify-content:space-between;align-items:center;z-index:4}.basic-date{font:500 20px/1 var(--font),sans-serif;color:var(--text)}.basic-domain{font:500 22px/1 var(--font),sans-serif;color:var(--text);letter-spacing:.05em}`
  },
  {
    id: 'editorial',
    name: 'Sobarkotha 1',
    description: 'PNG ব্যাকগ্রাউন্ডের ওপর ছবি, শিরোনাম ও ওয়েবসাইট বসানো সংবাদ-কেন্দ্রিক লেআউট।',
    defaults: { accentColor: '#ffffff', bgColor: '#b40000', textColor: '#ffffff', heading: 'শিরোনাম লিখুন', subheading: 'বিস্তারিত তথ্য', headingSize: 56, subheadingSize: 32, date: '১৯ সেপ্টেম্বর ২০২৬', domain: 'www.sobarkotha.com' },
    html: `<div class="template-wrapper sobarkotha1-template" style="--accent:{accentColor};--bg:{bgColor};--text:{textColor};--font:'{font}';--heading-size:{headingSize}px;--subheading-size:{subheadingSize}px;" data-canvas-width="1080" data-canvas-height="1080"><div class="template-background"></div><div class="sb1-image-wrapper"><img class="sb1-image" src="{image}" alt="Main image"></div><div class="sb1-baked-logo" aria-hidden="true"></div><div class="sb1-text-container"><h1 class="sb1-heading">{heading}</h1><p class="sb1-subheading">{subheading}</p></div></div>`,
    css: `.sobarkotha1-template{width:1080px;height:1080px;overflow:hidden;position:relative;background:var(--bg)}.sobarkotha1-template .template-background{background-image:url('./assets/sobarkotha1-template.png')}.sb1-image-wrapper{position:absolute;left:8px;top:8px;width:1064px;height:620px;overflow:hidden;z-index:1}.sb1-image{width:100%;height:100%;object-fit:cover;display:block;transform-origin:center center}.sb1-baked-logo{position:absolute;left:922px;top:12px;width:150px;height:112px;background-image:url('./assets/sobarkotha1-template.png');background-repeat:no-repeat;background-size:1080px 1080px;background-position:-922px -12px;z-index:3;pointer-events:none}.sb1-text-container{position:absolute;left:50px;right:50px;top:660px;z-index:4;text-align:center}.sb1-heading{font:700 var(--heading-size)/1.2 var(--font),sans-serif;color:var(--text);margin:0;letter-spacing:-.02em;text-shadow:0 2px 4px rgba(0,0,0,.2)}.sb1-subheading{font:500 var(--subheading-size)/1.3 var(--font),sans-serif;color:var(--accent);margin:10px 0 0;letter-spacing:-.01em;text-shadow:0 1px 2px rgba(0,0,0,.1)}.sb1-footer{position:absolute;bottom:20px;left:50px;right:50px;display:flex;justify-content:space-between;align-items:center;z-index:4}.sb1-date{font:500 20px/1 var(--font),sans-serif;color:var(--text);display:none}.sb1-domain{font:500 24px/1 Arial,sans-serif;color:var(--text);letter-spacing:.15em}`
  },
  {
    id: 'broadcast',
    name: 'Sobarkotha 2',
    description: '১০৮০×১৩৫০ PNG ব্যাকগ্রাউন্ডের ওপর ছবি, লেখা ও ওয়েবসাইটসহ দ্বি-টোনাল লেআউট।',
    defaults: { accentColor: '#ffeb3b', bgColor: '#061a91', textColor: '#ffffff', heading: 'শিরোনাম লিখুন', subheading: 'বিস্তারিত বিবরণ যোগ করুন', headingSize: 62, subheadingSize: 44, date: '১৯ সেপ্টেম্বর ২০২৬', domain: 'www.sobarkotha.com' },
    html: `<div class="template-wrapper sobarkotha2-template" style="--accent:{accentColor};--bg:{bgColor};--text:{textColor};--font:'{font}';--heading-size:{headingSize}px;--subheading-size:{subheadingSize}px;" data-canvas-width="1080" data-canvas-height="1350"><div class="template-background"></div><div class="sb2-image-section"><img class="sb2-image" src="{image}" alt="Main image"></div><div class="sb2-baked-logo" aria-hidden="true"></div><div class="sb2-date-overlay">{date}</div><div class="sb2-text-container"><h1 class="sb2-heading">{heading}</h1><p class="sb2-subheading">{subheading}</p></div></div>`,
    css: `.sobarkotha2-template{width:1080px;height:1350px;overflow:hidden;position:relative;background:#fff}.sobarkotha2-template .template-background{background-image:url('./assets/sobarkotha2-template.png')}.sb2-image-section{position:absolute;left:0;top:0;width:1080px;height:680px;overflow:hidden;z-index:1}.sb2-image{width:100%;height:100%;object-fit:cover;display:block;transform-origin:center center}.sb2-baked-logo{position:absolute;left:918px;top:20px;width:132px;height:100px;background-image:url('./assets/sobarkotha2-template.png');background-repeat:no-repeat;background-size:1080px 1350px;background-position:-918px -20px;z-index:3;pointer-events:none}.sb2-date-overlay{position:absolute;right:35px;top:600px;background:rgba(196,30,58,.9);color:#fff;padding:8px 18px;font:500 22px/1 var(--font),sans-serif;z-index:4;border-radius:2px}.sb2-text-container{position:absolute;left:60px;right:60px;top:800px;z-index:4;text-align:center}.sb2-heading{font:700 var(--heading-size)/1.2 var(--font),sans-serif;color:#fff;margin:0;letter-spacing:-.02em}.sb2-subheading{font:500 var(--subheading-size)/1.25 var(--font),sans-serif;color:var(--accent);margin:12px 0 0;letter-spacing:-.02em}.sb2-footer{position:absolute;bottom:30px;left:60px;right:60px;display:flex;justify-content:space-between;align-items:center;z-index:4}.sb2-domain-left{font:500 20px/1 var(--font),sans-serif;color:#888}.sb2-domain-right{font:500 20px/1 var(--font),sans-serif;color:#fff;letter-spacing:.05em}`
  }
];
