export const templates = [
  {
    id: 'classic',
    name: 'Basic',
    description: 'গ্রে ব্যাকগ্রাউন্ড সহ মূল ডিজাইন। কেন্দ্রীয় ইমেজ সহ পেশাদার লেআউট।',
    defaults: { accentColor: '#c41e3a', bgColor: '#e8e8e8', textColor: '#000000', heading: 'শিরোনাম লিখুন', subheading: 'বিস্তারিত বর্ণনা যোগ করুন', date: '', domain: 'sobarkotha.com' },
    html: `<div class="template-wrapper basic-template" style="--accent:{accentColor};--bg:{bgColor};--text:{textColor};--font:'{font}';" data-canvas-width="1080" data-canvas-height="1080"><div class="basic-bg"></div><div class="basic-image-wrapper"><img class="basic-image" src="{image}" alt="Main image"></div><img class="basic-logo" src="{logo}" alt="Logo"><div class="basic-text-area"><h1 class="basic-heading">{heading}</h1><p class="basic-subheading">{subheading}</p></div><div class="basic-footer"><span class="basic-date">{date}</span><span class="basic-domain">{domain}</span></div></div>`,
    css: `.basic-template{width:1080px;height:1080px;overflow:hidden;position:relative;background:var(--bg)}.basic-bg{position:absolute;inset:0;background:linear-gradient(135deg,var(--bg) 0%,rgba(150,150,150,0.3) 100%);z-index:0}.basic-image-wrapper{position:absolute;left:40px;top:40px;width:1000px;height:520px;border-radius:20px;overflow:hidden;z-index:1;box-shadow:0 8px 32px rgba(0,0,0,0.15)}.basic-image{width:100%;height:100%;object-fit:cover;display:block}.basic-logo{position:absolute;left:50%;transform:translateX(-50%);top:580px;width:160px;height:120px;object-fit:contain;z-index:3}.basic-text-area{position:absolute;left:45px;right:45px;top:720px;z-index:4;text-align:center}.basic-heading{font:700 48px/1.2 var(--font),sans-serif;color:var(--text);margin:0;letter-spacing:-0.02em}.basic-subheading{font:500 28px/1.3 var(--font),sans-serif;color:var(--accent);margin:8px 0 0;letter-spacing:-0.01em}.basic-footer{position:absolute;bottom:25px;left:45px;right:45px;display:flex;justify-content:space-between;align-items:center;z-index:4}.basic-date{font:500 20px/1 var(--font),sans-serif;color:var(--text)}.basic-domain{font:500 22px/1 var(--font),sans-serif;color:var(--text);letter-spacing:0.05em}`
  },
  {
    id: 'editorial',
    name: 'Sobarkotha 1',
    description: 'লাল ব্যাকগ্রাউন্ড সহ শক্তিশালী ডিজাইন। সংবাদ-কেন্দ্রিক লেআউট।',
    defaults: { accentColor: '#ffffff', bgColor: '#b40000', textColor: '#ffffff', heading: 'শিরোনাম লিখুন', subheading: 'বিস্তারিত তথ্য', date: '১৯ সেপ্টেম্বর ২০২৬', domain: 'www.sobarkotha.com' },
    html: `<div class="template-wrapper sobarkotha1-template" style="--accent:{accentColor};--bg:{bgColor};--text:{textColor};--font:'{font}';" data-canvas-width="1080" data-canvas-height="1080"><div class="sb1-bg"></div><img class="sb1-image" src="{image}" alt="Main image"><img class="sb1-logo" src="{logo}" alt="Logo"><div class="sb1-text-container"><h1 class="sb1-heading">{heading}</h1><p class="sb1-subheading">{subheading}</p></div><div class="sb1-footer"><span class="sb1-date">{date}</span><span class="sb1-domain">{domain}</span></div></div>`,
    css: `.sobarkotha1-template{width:1080px;height:1080px;overflow:hidden;position:relative;background:var(--bg)}.sb1-bg{position:absolute;inset:0;background:var(--bg);z-index:0}.sb1-image{position:absolute;left:8px;top:8px;width:1064px;height:620px;object-fit:cover;z-index:1;border-radius:2px}.sb1-logo{position:absolute;right:20px;top:18px;width:160px;height:110px;object-fit:contain;z-index:3}.sb1-text-container{position:absolute;left:50px;right:50px;top:660px;z-index:4;text-align:center}.sb1-heading{font:700 56px/1.2 var(--font),sans-serif;color:var(--text);margin:0;letter-spacing:-0.02em;text-shadow:0 2px 4px rgba(0,0,0,0.2)}.sb1-subheading{font:500 32px/1.3 var(--font),sans-serif;color:var(--accent);margin:10px 0 0;letter-spacing:-0.01em;text-shadow:0 1px 2px rgba(0,0,0,0.1)}.sb1-footer{position:absolute;bottom:20px;left:50px;right:50px;display:flex;justify-content:space-between;align-items:center;z-index:4}.sb1-date{font:500 20px/1 var(--font),sans-serif;color:var(--text);display:none}.sb1-domain{font:500 24px/1 Arial,sans-serif;color:var(--text);letter-spacing:0.15em}`
  },
  {
    id: 'broadcast',
    name: 'Sobarkotha 2',
    description: 'নীল-লাল দ্বি-টোনাল ডিজাইন। সর্বোচ্চ প্রভাব সহ আধুনিক লেআউট।',
    defaults: { accentColor: '#ffeb3b', bgColor: '#061a91', textColor: '#ffffff', heading: 'শিরোনাম লিখুন', subheading: 'বিস্তারিত বিবরণ যোগ করুন', date: '১৯ সেপ্টেম্বর ২০২৬', domain: 'www.sobarkotha.com' },
    html: `<div class="template-wrapper sobarkotha2-template" style="--accent:{accentColor};--bg:{bgColor};--text:{textColor};--font:'{font}';" data-canvas-width="1080" data-canvas-height="1350"><div class="sb2-image-section"><img class="sb2-image" src="{image}" alt="Main image"></div><img class="sb2-logo" src="{logo}" alt="Logo"><div class="sb2-date-overlay">{date}</div><div class="sb2-red-section"></div><div class="sb2-blue-section"></div><div class="sb2-text-container"><h1 class="sb2-heading">{heading}</h1><p class="sb2-subheading">{subheading}</p></div><div class="sb2-footer"><span class="sb2-domain-left">বিভাগ কন্টেন্ট</span><span class="sb2-domain-right">{domain}</span></div></div>`,
    css: `.sobarkotha2-template{width:1080px;height:1350px;overflow:hidden;position:relative;background:#fff}.sb2-image-section{position:absolute;left:0;top:0;width:1080px;height:680px;overflow:hidden;z-index:1}.sb2-image{width:100%;height:100%;object-fit:cover;display:block}.sb2-logo{position:absolute;right:30px;top:25px;width:150px;height:110px;object-fit:contain;z-index:3}.sb2-date-overlay{position:absolute;right:35px;top:600px;background:rgba(196,30,58,0.9);color:#fff;padding:8px 18px;font:500 22px/1 var(--font),sans-serif;z-index:2;border-radius:2px}.sb2-red-section{position:absolute;left:0;top:680px;width:1080px;height:60px;background:#c41e3a;z-index:1}.sb2-blue-section{position:absolute;left:0;top:740px;width:1080px;height:610px;background:var(--bg);z-index:1}.sb2-text-container{position:absolute;left:60px;right:60px;top:800px;z-index:4;text-align:center}.sb2-heading{font:700 62px/1.2 var(--font),sans-serif;color:#fff;margin:0;letter-spacing:-0.02em}.sb2-subheading{font:500 44px/1.25 var(--font),sans-serif;color:var(--accent);margin:12px 0 0;letter-spacing:-0.01em}.sb2-footer{position:absolute;bottom:30px;left:60px;right:60px;display:flex;justify-content:space-between;align-items:center;z-index:4}.sb2-domain-left{font:500 20px/1 var(--font),sans-serif;color:#888}.sb2-domain-right{font:500 20px/1 var(--font),sans-serif;color:#fff;letter-spacing:0.05em}`
  }
];
